
services:
  db:
    container_name: experience_db_1
    restart: always
    build:
      context: docker/postgres/
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: experience
      POSTGRES_PASSWORD: experience
      POSTGRES_DB: experience
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - experiencenet

  minio:
    container_name: experience_minio_1
    restart: always
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - experiencenet
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12345678
      MINIO_DOMAIN: localhost
    volumes:
      - minio:/data
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data

  mail:
    container_name: experience_mail_1
    restart: always
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - experiencenet

  supabase-studio:
    container_name: experience_supabase_studio_1
    image: supabase/studio:2025.12.08-sha-0399beb
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      SUPABASE_URL: http://kong:8000
      SUPABASE_PUBLIC_URL: ${AUTH_HOST}
      STUDIO_PG_META_URL: http://meta:8080
      SUPABASE_ANON_KEY: ${AUTH_API_KEY}
      SUPABASE_SERVICE_KEY: ${AUTH_API_KEY}
    networks:
      - experiencenet
    depends_on:
      - kong
      - meta

  kong:
    container_name: experience_kong_1
    image: kong:2.8.1
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
    volumes:
      - ./docker/supabase/kong.yml:/var/lib/kong/kong.yml:ro
    networks:
      - experiencenet
    depends_on:
      - auth
      - rest

  auth:
    container_name: experience_auth_1
    image: supabase/gotrue:v2.99.0
    restart: unless-stopped
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${AUTH_HOST}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}?search_path=auth
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_URI_ALLOW_LIST: "*"
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: ${JWT_AUD}
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
      GOTRUE_MAILER_AUTOCONFIRM: "false"
      GOTRUE_SMTP_HOST: mail
      GOTRUE_SMTP_PORT: 1025
      GOTRUE_SMTP_USER: ""
      GOTRUE_SMTP_PASS: ""
      GOTRUE_SMTP_ADMIN_EMAIL: admin@experience.com
      GOTRUE_MAILER_URLPATHS_INVITE: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_RECOVERY: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: /auth/v1/verify
    networks:
      - experiencenet
    depends_on:
      - db

  rest:
    container_name: experience_rest_1
    image: postgrest/postgrest:v11.2.0
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}
      PGRST_DB_SCHEMAS: public,auth
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"
    networks:
      - experiencenet
    depends_on:
      - db

  meta:
    container_name: experience_meta_1
    image: supabase/postgres-meta:v0.68.0
    restart: unless-stopped
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: ${DB_NAME}
      PG_META_DB_USER: ${DB_USERNAME}
      PG_META_DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - experiencenet
    depends_on:
      - db

networks:
  experiencenet:
    driver: "bridge"

volumes:
  data:
    driver: "local"
  minio:
    driver: "local"

